kernel: sched: deadline: remove unused variable
../kernel/sched/deadline.c:1156:18: error: unused variable 'scaled_delta_exec' [-Werror,-Wunused-variable]
        u64 delta_exec, scaled_delta_exec;
                        ^
../kernel/sched/deadline.c:1157:6: error: unused variable 'cpu' [-Werror,-Wunused-variable]
        int cpu = cpu_of(rq);
            ^
2 errors generated.

Signed-off-by: onettboots <blackcocopet@gmail.com>